examples/src/main/java/com/expediagroup/sdk/rapid/examples/scenarios/booking/MultiRoomHoldAndResumeBookScenario.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/scenarios/booking/SingleRoomBookScenario.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/services/GeographyService.java

SDK-1319 update geography api calls to the latest SDK methods

---

code/pom.xml
code/src/main/kotlin/com/expediagroup/sdk/core/model/Response.kt
code/src/main/kotlin/com/expediagroup/sdk/rapid/client/rapidClient.kt

chore: update code to v4.1.2

---

examples/README.md
examples/src/main/java/com/expediagroup/sdk/rapid/examples/services/RapidService.java

SDK-1321 add readme file with instructions to run the examples

---

code/pom.xml
code/src/main/kotlin/com/expediagroup/sdk/rapid/client/rapidClient.kt
code/src/main/kotlin/com/expediagroup/sdk/rapid/models/ManagementResponse.kt
code/src/main/kotlin/com/expediagroup/sdk/rapid/models/Review.kt
code/src/main/kotlin/com/expediagroup/sdk/rapid/operations/GetPropertyGuestReviewsOperationParams.kt

chore: update code to v4.2.0

---

examples/pom.xml
examples/src/main/java/com/expediagroup/sdk/rapid/examples/RapidSdkDemoApplication.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/scenarios/booking/AsyncSingleRoomBookScenario.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/services/BookService.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/services/RapidService.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/services/ShopService.java

- Adding another scenario that demonstrates how to shop and book a single room using the new executeAsync method for asynchronous execution of operations.
- Update some of the existing scenarios to remove all the null checks, while we realize its recommended to keep them, our goal is to keep the example scenarios focused on the usage of the operations and the scenarios they can be used in.
- [SDK-1389](https://jira.expedia.biz/browse/SDK-1389)

SDK-1389 Add an example on using async execution to shop-book a room

---

README.md

chore: update docs link in readme file

chore: update docs link in readme file

---

.github/workflows/run-examples.yaml

chore: remove jar install step from run examples action

---

.github/workflows/run-examples.yaml

chore: migrate run examples action to new self serve changes

---

.github/workflows/generate-and-publish-sdk.yaml
specs.yaml

This is to use the new Self Service action to:
- upload specs
- transform specs
- generate SDK
- publish sources
- publish SDK
The full action is [here](https://github.com/ExpediaGroup/expediagroup-java-sdk/blob/main/.github/workflows/selfserve-full-workflow.yaml).
A sample run of a similar action in the demo repo is available [here](https://github.com/mohnoor94/sdk-generator-user/actions/runs/10441304015/job/28912333973#step:6:162).
This PT also includes a copy of the current Rapid specs for future releases.
Internal Ticket: SDK-1233

feat: SDK-1233 use self-serve full workflow action

---

.github/workflows/generate-and-publish-sdk.yaml
.github/workflows/run-examples.yaml
examples/pom.xml
examples/src/main/java/com/expediagroup/sdk/rapid/examples/services/GeographyService.java

Update examples to use v5.0.0-SNAPSHOT

fix: update examples

---

examples/pom.xml
examples/src/main/java/com/expediagroup/sdk/rapid/examples/RapidSdkDemoApplication.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/scenarios/booking/AsyncSingleRoomBookScenario.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/scenarios/booking/CompletePaymentSessionScenario.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/scenarios/booking/MultiRoomHoldAndResumeBookScenario.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/scenarios/booking/RegisterPaymentSessionScenario.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/scenarios/content/GetPropertyContentInAdditionalLanguageScenario.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/scenarios/content/GetPropertyContentScenario.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/scenarios/geography/GetListOfRegionNamesScenario.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/scenarios/geography/GetRegionByAncestorIdScenario.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/scenarios/geography/GetRegionDetailsAndPropertyIdsScenario.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/scenarios/geography/ParseRegionAncestorsScenario.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/scenarios/geography/ParseRegionCategoriesScenario.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/scenarios/geography/ParseRegionCoordinatesScenario.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/scenarios/geography/ParseRegionDescendantsScenario.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/scenarios/geography/ParseRegionWithMultiPolygonCoordinatesScenario.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/scenarios/managebooking/CancelHeldBookingScenario.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/scenarios/managebooking/ChangeRoomDetailsScenario.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/scenarios/managebooking/CommitHardChangeScenario.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/scenarios/managebooking/DeleteRoomScenario.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/scenarios/shopping/GetAdditionalAvailabilityOfPropertyScenario.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/scenarios/shopping/GetPaymentOptionsOfRoomScenario.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/services/BookService.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/services/ContentService.java
examples/src/main/java/com/expediagroup/sdk/rapid/examples/services/ShopService.java

- Add examples on using typed links
- Excluding links for register payment scenario and complete payment scenario.
- CommitHardChange scenario is incomplete until bug is fixed with SDK.
-

SDK-1385 add examples on links

---

.github/workflows/generate-and-publish-sdk-sources.yaml
customizations/generator/openapi/src/main/kotlin/com/expediagroup/sdk/generators/openapi/OpenApiSdkGenerator.kt
customizations/generator/openapi/src/main/resources/templates/expediagroup-sdk/client.mustache
customizations/generator/openapi/src/main/resources/templates/expediagroup-sdk/operation_params.mustache

Update custom generator templates to work with the latest generator tag

chore: update generation customizations to use latest generator tag

---

.github/workflows/generate-and-publish-sdk-sources.yaml

chore: update generator version

---

.github/workflows/release-sdk.yaml
.github/workflows/run-examples.yaml

No testing before publishing a new SDK version
Run example scenarios as tests using generated SDK
Added a new GH action to run examples before publishing SDK
Tested changes manually
A new SDK version is published only if the examples run successfully

chore: run examples before publishing SDKs

---

customizations/generator/openapi/src/main/kotlin/com/expediagroup/sdk/generators/openapi/OpenApiSdkGenerator.kt
customizations/generator/openapi/src/main/resources/templates/expediagroup-sdk/client.mustache
customizations/generator/openapi/src/main/resources/templates/expediagroup-sdk/operation_params.mustache

Non-body request params are not validated according to the constraints defined in the specs
Validate request params according to the constraints defined in the specs
Add Hibernate tags to operation params, and validate params object while building it
Tested manually
Request params are validated according to the constraints defined in the specs. Violations throw `PropertyConstraintViolationException`

feat: validate operation params

---

docs/tree.yml

The page is merged but its not visible in PR preview
Add page to rapid tree
Added page to rapid tree
N/A
N/A
-

fix: add the okhttpclient page to rapid tree

---

docs/java/okhttpclient.md

Found a typo in docs
Fixing typo & some improvements to wording

fix: typo and minor wording modifications

---

specs.yaml

chore: update specs

---

.github/workflows/generate-and-publish-sdk-sources.yaml
.github/workflows/release-sdk.yaml

Updated the version of the generate SDK GH action

chore: update generate SDK action version

---

docs/java/okhttpclient.md

Current version mentioned in article has a bug
update version to the stable one
updated version
N/A
N/A
None

Correct version in okhttpclient article

---

customizations/generator/openapi/src/main/resources/templates/expediagroup-sdk/api.mustache
examples/src/main/java/com/expediagroup/sdk/rapid/examples/services/RapidService.java

Operations annotated as deprecated in an OpenAPI specs are marked as such in the generated code

feat: annotate deprecated operations as such

---

specs.yaml

Rapid specs are updated
Release a new version of the SDK
Update specs file to latest
Tested with examples
Successful run of examples
N/A

chore: update specs to latest
